version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - pip install --upgrade awscli

  pre_build:
    commands:
      - cd lambdas/api
      - pip install -r requirements.txt --target .
      - cd ../process-source
      - cd ../..
  
  build:
    commands:
      - aws cloudformation package --template templates/root.yaml --s3-bucket $S3_BUCKET --s3-prefix $S3_BUCKET_PREFIX --output-template root-export.yaml

artifacts:
  type: zip
  files:
    - root-export.yaml