AWSTemplateFormatVersion: 2010-09-09
Transform:
- AWS::Serverless-2016-10-31

Parameters:
  ScheduleExpression:
    Type: String
  EventBusName:
    Description: Name of event bus
    Type: String

Outputs:
  SourcesTableName:
    Description: Name of RSS source table
    Value: !Ref SourcesTable
  SourcesTableArn:
    Description: ARN of RSS source table
    Value: !GetAtt SourcesTable.Arn
  EventBusName:
    Description: Name of event bus
    Value: !Ref EventBus
  EventBusArn:
    Description: ARN of event bus
    Value: !GetAtt EventBus.Arn

Resources:

  SourcesTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: source
        Type: String

  EventBus:
    Type: AWS::Events::EventBus
    Properties:
      Name: !Ref EventBusName

  ItemsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions: 
        -
          AttributeName: source
          AttributeType: S
        -
          AttributeName: guid
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        -
          AttributeName: source
          KeyType: HASH
        -
          AttributeName: guid
          KeyType: RANGE


  ChannelQueue:
    Type: AWS::SQS::Queue
    Properties:
      VisibilityTimeout: 90

  ItemQueue:
    Type: AWS::SQS::Queue
    Properties:
      FifoQueue: true
      VisibilityTimeout: 30
      ContentBasedDeduplication: true
      MessageRetentionPeriod: 240


  ListSourcesFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: python3.8
      CodeUri: lambdas/list-sources
      Timeout: 30
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref SourcesTableName
        - SQSSendMessagePolicy:
            QueueName: !GetAtt ChannelQueue.QueueName
      Environment:
        Variables:
          DYNAMO_TABLE: !Ref SourcesTableName
          QUEUE_URL: !Ref ChannelQueue
      Events:
        ScheduleEvent:
          Type: Schedule
          Properties:
            Schedule: !Ref ScheduleExpression
            Enabled: True


  ProcessChannelFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: python3.8
      CodeUri: lambdas/process-source
      Timeout: 60
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref ItemsTable
        - SQSPollerPolicy:
            QueueName: !GetAtt ChannelQueue.QueueName
        - SQSSendMessagePolicy:
            QueueName: !GetAtt ItemQueue.QueueName
      Environment:
        Variables:
          DYNAMO_TABLE: !Ref ItemsTable
          CHANNEL_QUEUE_URL: !Ref ChannelQueue
          ITEM_QUEUE_URL: !Ref ItemQueue
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt ChannelQueue.Arn
            Enabled: True


  ProcessItemFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: python3.8
      CodeUri: lambdas/process-item
      Timeout: 15
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ItemsTable
        - SQSPollerPolicy:
            QueueName: !GetAtt ItemQueue.QueueName
        - EventBridgePutEventsPolicy:
            EventBusName: !Ref EventBus
      Environment:
        Variables:
          DYNAMO_TABLE: !Ref ItemsTable
          ITEM_QUEUE_URL: !Ref ItemQueue
          EVENT_BUS_NAME: !Ref EventBus
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt ItemQueue.Arn
            Enabled: True