AWSTemplateFormatVersion: 2010-09-09
Transform:
- AWS::Serverless-2016-10-31

Outputs:
  RestApiId:
    Description: Rest API ID
    Value: !Ref Api

Parameters:
  SourcesTableName:
    Type: String
  EventBusName:
    Type: String

Resources:

  ApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: python3.8
      CodeUri: ../lambdas/api
      Timeout: 30
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref SourcesTableName
        
      Environment:
        Variables:
          DYNAMO_TABLE: !Ref SourcesTableName
          EVENT_BUS_NAME: !Ref EventBusName
      Events:
        GetSourcesEvent:
          Type: Api
          Properties:
            Path: /sources
            Method: get
            RestApiId: !Ref Api
        CreateSourcesEvent:
          Type: Api
          Properties:
            Path: /sources
            Method: post
            RestApiId: !Ref Api
        DeleteSourceEvent:
          Type: Api
          Properties:
            Path: /sources
            Method: delete
            RestApiId: !Ref Api
        GetSubscriptionsEvent:
          Type: Api
          Properties:
            Path: /subscriptions
            Method: get
            RestApiId: !Ref Api
        CreateSubscriptionEvent:
          Type: Api
          Properties:
            Path: /subscriptions
            Method: post
            RestApiId: !Ref Api
        DeleteSubscriptionEvent:
          Type: Api
          Properties:
            Path: /subscriptions/{id}
            Method: delete
            RestApiId: !Ref Api

  Api:
    Type: AWS::Serverless::Api
    Properties:
      StageName: live
      Cors:
        AllowMethods: "'*'"
        AllowHeaders: "'*'"
        AllowOrigin: "'*'"