AWSTemplateFormatVersion: 2010-09-09
Transform:
- AWS::Serverless-2016-10-31

Outputs:
  RestApiId:
    Description: Rest API ID
    Value: !Ref Api

Parameters:
  SourcesTableName:
    Type: String
  TopicName:
    Type: String
  TopicArn:
    Type: String

Resources:

  ApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: python3.7
      CodeUri: ../lambdas/api
      Timeout: 30
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref SourcesTableName
        - SNSCrudPolicy:
            TopicName: !Ref TopicName
      Environment:
        Variables:
          DYNAMO_TABLE: !Ref SourcesTableName
          TOPIC_ARN: !Ref TopicArn
      Events:
        GetSourcesEvent:
          Type: Api
          Properties:
            Path: /sources
            Method: get
            RestApiId: !Ref Api

  Api:
    Type: AWS::Serverless::Api
    Properties:
      StageName: live
      Cors:
        AllowMethods: "'*'"
        AllowHeaders: "'*'"
        AllowOrigin: "'*'"