AWSTemplateFormatVersion: 2010-09-09
Transform:
- AWS::Serverless-2016-10-31

Parameters:
  ScheduleExpression:
    Type: String

Outputs:
  SourcesTableName:
    Description: Name of RSS source table
    Value: !Ref SourcesTable
  SourcesTableArn:
    Description: ARN of RSS source table
    Value: !GetAtt SourcesTable.Arn
  EventBusName:
    Description: Name of event bus
    Value: !Ref EventBus
  EventBusArn:
    Description: ARN of event bus
    Value: !GetAtt EventBus.Arn

Resources:

  SourcesTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: source
        Type: String

  EventBus:
    Type: AWS::Events::EventBus
    Properties:
      Name: String

  FeedReaderStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: feed-reader.yaml
      Parameters:
        SourcesTableName: !Ref SourcesTable
        EventBusName: !Ref EventBus
        ScheduleExpression: !Ref ScheduleExpression

  ApiStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: api.yaml
      Parameters:
        SourcesTableName: !Ref SourcesTable
        EventBusName: !Ref EventBus

  WebsiteStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: website.yaml
      Parameters:
        RestApiId: !GetAtt [ApiStack, Outputs.RestApiId]